// Cows and Bulls Game - Without Arrays, Strings, Pointers, Structs, break and continue... (On purpose).
// Written by: Ofek Carpassi.

// stdio.h - Standard Input/Output Header
// stdlib.h - Standard Library Header - for rand() and srand()
// time.h - Time Header - for time()
// conio.h - Console Input/Output Header - for getch()
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <conio.h>

// Enum for boolean values
enum bollean {FALSE, TRUE};
// Enum for difficulty levels
enum DifficultyLevel {EASY = 1, MEDIUM, HARD, CRAZY};
// Enum for difficulty rounds
enum DifficultyRounds { EASY_ROUNDS = 20, MEDIUM_ROUNDS = 15, HARD_ROUNDS = 10, MAX_RANDOM_CRAZY = 21, MIN_RANDOM_CRAZY = 5};

#define DIGITS_IN_NUMBER 4 // Amount of digits in the random number
#define MIN_DIGIT 1 // Minimum digit in the random number
#define MAX_DIGIT 6 // Maximum digit in the random number
#define REMOVE_AND_GET_LAST_DIGIT 10 // A number to remove and get the last digit with % and /
#define LOOP_RESET -1 // A number to reset the loop
#define MIN_DIGIT_CHAR '1' // Minimum digit character
#define MAX_DIGIT_CHAR '6' // Maximum digit character
#define BASE_DIGIT_CHAR '0' // Base digit character

void printWelcomeAndRules(); // This function prints the welcome message and the rules of the game.

void getDifficultyLevel(); // This function gets the difficulty level from the user and saves it in a global variable.

void getRandomNumber(); // This function generates a random number based on the difficulty level and saves it in a global variable.

void playDifficulty(); // This function plays the game based on the difficulty level.

void playGame(int amountOfGuesses); // This function plays the game. It takes the number of guesses allowed as a parameter.

int getGuess(int amountOfGuesses); // This function gets a guess from the user and returns it. It takes the number of guesses left as a parameter.

void checkGuess(int guess); // This function checks the user's guess. It takes the guess as a parameter.

// Global variables
int difficultyLevel = 0; // The difficulty level chosen by the user
int randomNumber = 0; // The random number generated by the computer
int hits = 0; // The number of hits
int misses = 0; // The number of misses

// Main function - The entry point of the program - calls all the other functions
int main()
{
    // Seed the random number generator
    srand(time(0));

    // playAgain - A flag to indicate if the user wants to play again
    char playAgain = ' ';

    // Print welcome message and rules
    printWelcomeAndRules();

    // Play the game as long as the user wants to play again
    do
    {
        // Get the difficulty level from the user
        getDifficultyLevel();
        // Generate a random number
        getRandomNumber();
        // Play the game according to the difficulty level
        playDifficulty();

        // Ask the user if they want to play again
        do {
            // Get the user's response
            printf("Do you want to play again? (y/n): ");
            playAgain = getch();

            // New line
            printf("\n");
        } while (playAgain != 'y' && playAgain != 'n');

        // If the user doesn't want to play again, break out of the loop and stop the program
        if (playAgain == 'n') {
            // Print goodbye message
            printf("Goodbye!\n");
            return 0;
        }

    } while (TRUE);

    return 0;
}

// printWelcomeAndRules - Print welcome message and rules
void printWelcomeAndRules()
{
    // Print welcome message and rules
    printf("The game is called \"Bulls and Cows\".\n");
    printf("The game is played between you and the computer.\n");
    printf("The computer will choose a secret password of 4 distinct digits.\n");
    printf("Your goal is to guess the password.\n");
    printf("The rules are as follows:\n");
    printf("1. In each round you try to guess the secret password (4 distinct digits)\n");
    printf("2. After every guess you'll receive two hints about the password\n");
    printf("   HITS:   The number of digits in your guess which were exactly right.\n");
    printf("   MISSES: The number of digits in your guess which belongs to\n");
    printf("           the password but were miss-placed.\n");
    printf("3. If you'll fail to guess the password after a certain number of rounds\n");
    printf("   You will lose!\n\n");
}

// getDifficultyLevel - Get the difficulty level from the user
void getDifficultyLevel()
{
    // Defining local variables - input - The input from the user
    int input = 0;

    // Print the options for the user
    printf("Please choose the game level:\n");
    printf("1 - Easy (20 rounds)\n");
    printf("2 - Moderate (15 rounds)\n");
    printf("3 - Hard (10 rounds)\n");
    printf("4 - Crazy (random number of rounds 5-25)\n");

    // Get the difficulty level from the user as long as he doesn't enter a valid difficulty level
    do {
        // Get the difficulty level from the user and save it in the input variable
        printf("Make a choice: ");

        // Check if the input is an integer, and if it is between 1 and 4
        if(scanf("%d", &input) == 1 && input >= EASY && input <= CRAZY)
        {
            // If the input is valid save it in the global variable and return
            difficultyLevel = input;
            return;
        }
        else
        {
            // If the input is not valid clear the input buffer
            while(getchar() != '\n');
        }
    } while(TRUE); // Run the loop as long as the user doesn't enter a valid difficulty level
}

// getRandomNumber - Generate a random number
void getRandomNumber()
{
    /*
    Defining local variables
    i - A counter for the loop
    j - A counter for the loop
    randomDigit - A random digit to build the random number
    tempRandomNumber - A temporary variable to save the random number
    */
    int i = 0, j = 0, randomDigit = 0, tempRandomNumber = 0;

    // Reset the random number
    randomNumber = 0;

    // Generate a random number without duplicate digits
    for(i = 0; i < DIGITS_IN_NUMBER; i++)
    {
        // Generate a random number between 1 and 6 (inclusive)
        randomDigit = rand() % MAX_DIGIT + MIN_DIGIT;

        // Save the random number in a temporary variable - to check if the digit is already in the random number
        tempRandomNumber = randomNumber;

        // Check if the digit is already in the random number
        for(j = 0; j < i; j++)
        {
            // If the digit is already in the random number
            if(randomDigit == tempRandomNumber % REMOVE_AND_GET_LAST_DIGIT)
            {
                // Generate a new digit
                randomDigit = rand() % MAX_DIGIT + MIN_DIGIT;

                // Reset the loop
                j = LOOP_RESET;

                // Reset the tempRandomNumber
                tempRandomNumber = randomNumber;

                // multiply the tempRandomNumber by 10 so it will have the same amount of digits
                tempRandomNumber *= 10;
            }
            // Remove the last digit from the tempRandomNumber
            tempRandomNumber /= REMOVE_AND_GET_LAST_DIGIT;
        }

        // Add the digit to the random number
        randomNumber = randomNumber * REMOVE_AND_GET_LAST_DIGIT + randomDigit;
    }
}

// playDifficulty - Play the game according to the difficulty level
void playDifficulty()
{
    // Play the game according to the difficulty level chosen by the user
    switch(difficultyLevel)
    {
        // Play the game according to the difficulty level
        case EASY:
            playGame(EASY_ROUNDS);
            break;
        case MEDIUM:
            playGame(MEDIUM_ROUNDS);
            break;
        case HARD:
            playGame(HARD_ROUNDS);
            break;
        case CRAZY:
            // send a random number between 5 - 25
            playGame(rand() % MAX_RANDOM_CRAZY + MIN_RANDOM_CRAZY);
            break;
    }
}

// playGame - Play the game with the given number of attempts
void playGame(int amountOfGuesses)
{
    // Save the amount of guesses in a constant variable - to print it at the end of the game
    const int GUESS_AMOUNT = amountOfGuesses;
    // guess - The amount of guesses the user used
    int guess = 0;
    // validGuess - A flag to indicate if the user entered a valid guess - set to FALSE
    int validGuess = FALSE;
    
    // Play the game as long as the user didn't guess the number and he still has attempts left
    while(guess != randomNumber && amountOfGuesses > 0)
    {
        validGuess = FALSE;

        // Get a guess from the user - using the getGuess function
        guess = getGuess(amountOfGuesses);

        // Check if the user entered a valid guess (if not, the getGuess function will return 0)
        if(guess != 0)
        {
            // Set the validGuess flag to TRUE - the user entered a valid guess
            validGuess = TRUE;
        }

        // Check if the user entered an invalid guess
        while (validGuess == FALSE)
        {
            // Print an error message and get a new guess from the user
            printf("Only 1-6 are allowed, try again!\n");
            guess = getGuess(amountOfGuesses);
            
            // If the user entered a valid guess - set the validGuess flag to TRUE
            if(guess != 0)
            {
                // Set the validGuess flag to TRUE - the user entered a valid guess
                validGuess = TRUE;
            }
        }

        // Decrease the amount of guesses left
        amountOfGuesses--;

        // Check the user's guess
        checkGuess(guess);

        // Print the number of hits and misses
        printf("You got \t %d HITS \t %d MISSES.\n", hits, misses);

        // If the user guessed the number
        if(guess == randomNumber)
        {
            // Print a winning message and the amount of guesses the user used
            printf("\t4 HITS YOU WON!!!\n\n");
            printf("It took you only %d guesses!\n", GUESS_AMOUNT - amountOfGuesses);
            // Return from the function
            return;
        }
    }
    // If the user didn't guess the number - print a losing message and the secret password
    printf("The secret password was %d\n", randomNumber);
    printf("You lost, try again!\n\n");
}

// getGuess - Get a guess from the user
int getGuess(int amountOfGuesses)
{
    // Defining local variables
    int i = 0, guess = 0, digit = 0, isVaildGuess = TRUE;

    // Print a message to the user
    printf("Write your guess (only 1-6, no ENTER is needed)\n");
    
    // If the difficulty level is not CRAZY print the amount of guesses left
    if(difficultyLevel != CRAZY)
    {
        printf("%d guesses left\n", amountOfGuesses);
    }
    else
    {
        // If the difficulty level is CRAZY print a message to the user
        printf("CRAZY MODE!!!\n");
    }

    // Get the four digits number from the user without the user hitting enter
    while (i < DIGITS_IN_NUMBER)
    {
        // Get a digit from the user using getch()
        digit = getch();

        // Print the digit to the screen
        printf("%c", digit);

        // If the user entered a digit between '1' and '6'
        if (digit >= MIN_DIGIT_CHAR && digit <= MAX_DIGIT_CHAR)
        {
            // Add the digit to the guess
            guess = guess * REMOVE_AND_GET_LAST_DIGIT + (digit - BASE_DIGIT_CHAR);
        }
        // If the user entered a digit that is not between '1' and '6' (or a character that is not a digit)
        else
        {
            // Set the isVaildGuess flag to FALSE
            isVaildGuess = FALSE;
        }
        // Increase the counter
        i++;
    }

    printf("\n");  // Print a newline to separate input from the next output

    // If the user entered an invalid guess - return 0
    if(isVaildGuess == FALSE)
    {
        return 0;
    }
    // If the user entered a valid guess - return the guess
    return guess;
}

// checkGuess - Check the user's guess against the random number
void checkGuess(int guess)
{
    /*
    Defining local variables
    i - A counter for the loop
    digit - A digit from the guess
    tempGuess - A temporary variable to save the guess
    tempRandomNumber - A temporary variable to save the random number
    */
    int i = 0, digit = 0, tempGuess = guess, tempRandomNumber = randomNumber;

    // Reset the hits and misses
    hits = 0;
    misses = 0;

    // Check the guess against the random number
    for(i = 0; i < DIGITS_IN_NUMBER; i++)
    {
        // Get the last digit from the guess
        digit = tempGuess % REMOVE_AND_GET_LAST_DIGIT;

        // Remove the last digit from the guess
        tempGuess /= REMOVE_AND_GET_LAST_DIGIT;

        // Check if the digit is in the random number and in the same place
        if(digit == tempRandomNumber % REMOVE_AND_GET_LAST_DIGIT)
        {
            // Increase the hits
            hits++;
        }
        // If the digit is not in the same place - check if the digit is in the random number
        else
        {
            /*
            Defining local variables
            j - A counter for the loop
            secondTempRandomNumber - A temporary variable to save the random number
            */
            int j = 0, secondTempRandomNumber = randomNumber;

            // Check if the digit is in the random number
            for(j = 0; j < DIGITS_IN_NUMBER; j++)
            {
                // If the digit is in the random number
                if(digit == secondTempRandomNumber % REMOVE_AND_GET_LAST_DIGIT)
                {
                    // Increase the misses
                    misses++;
                }

                // Remove the last digit from the random number
                secondTempRandomNumber /= REMOVE_AND_GET_LAST_DIGIT;
            }
        }

        // Remove the last digit from the random number
        tempRandomNumber /= REMOVE_AND_GET_LAST_DIGIT;
    }
}